import type { Metadata } from "next";
import { AuthProvider } from '../context/AuthContext';
import Header from '@/components/Header'; // Import Header
import Footer from '@/components/Footer'; // Import Footer
import { Toaster } from 'react-hot-toast';
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; // Uncommented

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased text-gray-800`}> {/* Added text-gray-800 */}
        <AuthProvider>
          <Toaster position="top-right" />
          <Header /> {/* Add Header */}
          {children}
          <Footer /> {/* Add Footer */}
        </AuthProvider>
      </body>
    </html>
  );
}
